"""Draws the Orbit icon and writes every platform's icon set from it.

The icon is the app's timer ring: a dim track with a warm depleting arc.
One drawing, three layers (background, ring, both), so each platform gets
the format it expects:

  iOS / watchOS   single 1024px PNG in an asset catalog
  Android / Wear  adaptive icon (gradient background + ring foreground)
                  plus square and round PNG fallbacks for older launchers

Requires rsvg-convert (brew install librsvg).

    python3 scripts/gen-icons.py
"""

import json
import math
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
C, R, W = 512, 292, 84
ARC_END = 292  # degrees of ring left, clockwise from 12 o'clock


def point(deg):
    rad = math.radians(deg - 90)
    return C + R * math.cos(rad), C + R * math.sin(rad)


def background():
    return """
  <radialGradient id="bg" cx="50%" cy="34%" r="80%">
    <stop offset="0" stop-color="#20232C"/>
    <stop offset="0.6" stop-color="#121419"/>
    <stop offset="1" stop-color="#0A0B0E"/>
  </radialGradient>""", '<rect width="1024" height="1024" fill="url(#bg)"/>'


def ring(scale=1.0):
    x1, y1 = point(0)
    x2, y2 = point(ARC_END)
    arc = f"M{x1:.1f} {y1:.1f} A{R} {R} 0 1 1 {x2:.1f} {y2:.1f}"
    defs = """
  <linearGradient id="arc" x1="0.85" y1="0.05" x2="0.15" y2="0.95">
    <stop offset="0" stop-color="#FFC56B"/>
    <stop offset="0.45" stop-color="#FF7A5C"/>
    <stop offset="1" stop-color="#FF4F6D"/>
  </linearGradient>
  <filter id="glow" x="-30%" y="-30%" width="160%" height="160%">
    <feGaussianBlur stdDeviation="34"/>
  </filter>"""
    body = f"""<g transform="translate({C} {C}) scale({scale}) translate({-C} {-C})">
  <circle cx="{C}" cy="{C}" r="{R}" stroke="#FFFFFF" stroke-opacity="0.07" stroke-width="{W}" fill="none"/>
  <path d="{arc}" stroke="url(#arc)" stroke-width="{W}" stroke-linecap="round" fill="none" opacity="0.55" filter="url(#glow)"/>
  <path d="{arc}" stroke="url(#arc)" stroke-width="{W}" stroke-linecap="round" fill="none"/>
  <circle cx="{x1:.1f}" cy="{y1:.1f}" r="{W * 0.22:.1f}" fill="#FFFFFF" fill-opacity="0.9"/>
</g>"""
    return defs, body


def svg(*layers):
    defs = "".join(d for d, _ in layers)
    body = "\n".join(b for _, b in layers)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">\n'
        f"<defs>{defs}\n</defs>\n{body}\n</svg>\n"
    )


def render(svg_text, out: Path, size: int, circle=False):
    out.parent.mkdir(parents=True, exist_ok=True)
    if circle:
        svg_text = svg_text.replace(
            "<defs>", '<defs><clipPath id="c"><circle cx="512" cy="512" r="512"/></clipPath>', 1
        ).replace("</defs>\n", '</defs>\n<g clip-path="url(#c)">\n', 1).replace("</svg>", "</g>\n</svg>")
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), "-o", str(out)],
        input=svg_text.encode(), check=True,
    )


def asset_catalog(folder: Path, platform: str, full: str):
    render(full, folder / "icon-1024.png", 1024)
    contents = {
        "images": [{"filename": "icon-1024.png", "idiom": "universal", "platform": platform, "size": "1024x1024"}],
        "info": {"author": "xcode", "version": 1},
    }
    (folder / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")


def android(res: Path, full: str, back: str, fore: str):
    densities = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
    for name, k in densities.items():
        d = res / f"mipmap-{name}"
        render(full, d / "ic_launcher.png", int(48 * k))
        render(full, d / "ic_launcher_round.png", int(48 * k), circle=True)
        render(back, d / "ic_launcher_background.png", int(108 * k))
        render(fore, d / "ic_launcher_foreground.png", int(108 * k))
    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen-icons.py -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""
    anydpi = res / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def main():
    full = svg(background(), ring())
    back = svg(background())
    # Adaptive foregrounds are masked to the central 66dp of 108dp; shrink the
    # ring so it sits inside that safe zone with the same breathing room.
    fore = svg(ring(scale=0.86))

    (ROOT / "assets/icon.svg").write_text(full)
    asset_catalog(ROOT / "ios/Orbit/Images.xcassets/AppIcon.appiconset", "ios", full)
    asset_catalog(ROOT / "watch/OrbitWatch/Assets.xcassets/AppIcon.appiconset", "watchos", full)
    (ROOT / "watch/OrbitWatch/Assets.xcassets/Contents.json").write_text(
        json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n"
    )
    android(ROOT / "android/app/src/main/res", full, back, fore)
    android(ROOT / "android/wear/src/main/res", full, back, fore)
    print("Icons written.")


if __name__ == "__main__":
    main()
